services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"  # LocalStack Edge Proxy
      - "8080:8080"  # LocalStack Dashboard
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - /Users/sbecker11/xyz/tmp/localstack:/tmp/localstack
      - /Users/sbecker11/xyz/tmp/.cache:/.cache
      - /var/run/docker.sock:/var/run/docker.sock
    user: "502:20"


# docker compose up localstack
# docker compose logs localstack