services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"  # localstack Edge Proxy
      - "${PORT_WEB_UI-8080}:8080"  # LocalStack Dashboard
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_CACHE_DIR=/.cache  # This might need adjustment based on LocalStack's configuration
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/sbecker11/xyz/tmp/dynamodb_data:/tmp/dynamodb_data   # chown 502:20 ~/dhynamodb_data
      - /Users/sbecker11/xyz/tmp/localstack:/tmp/localstack    # chown 502:20 ~/localstack_tmp
      - /Users/sbecker11/xyz/tmp/localstack/data:/tmp/localstack/data    # chown 502:20 ~/localstack_tmp
      - /Users/sbecker11/xyz/.cache:/.cache     # ran sudo chown 502:20 ~/localstack_cache
    user: 502:20  # same as "sbecker11:staff"


# put it up
# docker compose -f docker-compose-dynamodb-only.yml up

# check its status
# docker compose -f docker-compose-dynamodb-only.yml ps

# take it down
# docker compose -f docker-compose-dynamodb-only.yml down