#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# Activate virtual environment
source venv/bin/activate

# Install dependencies
pip install -r requirements.txt

PID_FILE="local_server.pid"

# Check if local server is running, if not, start it
if ! pgrep -f local_server.py > /dev/null; then
    python local_server.py &
    LOCAL_SERVER_PID=$!
    echo $LOCAL_SERVER_PID > $PID_FILE
    echo "local server started on port 5000 pid:$LOCAL_SERVER_PID"
else
    echo "local server already running"
fi

# Run pytest
pytest tests

# Deactivate virtual environment
deactivate

# Optionally, kill the local server if it was started by this script
if [ -f $PID_FILE ]; then
    LOCAL_SERVER_PID=$(cat $PID_FILE)
    kill $LOCAL_SERVER_PID
    rm $PID_FILE
    echo "killed local server with pid:${LOCAL_SERVER_PID}"
fi

