#!/bin/zsh
cat 
echo "PATH:$PATH"
which venv-activate
venv-activate

aws dynamodb list-tables --endpoint-url http://localhost:4566 --region us-west-2 | jq '.TableNames | length'

python scripts/count_tables.py