#!/bin/bash

# Exit immediately if a command exits with a non-zero status
# set -e

# Check if pytest target is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <pytest-target>"
  echo " example: $0 tests"
  echo " example: $0 tests/test_query_engine.py"
  echo " example: $0 tests/test_query_engine.py::TestQueryEngine"
  echo " example: $0 tests/test_query_engine.py::TestQueryEngine::test_basic_logging"

  exit 1
fi

PYTEST_TARGET=$1

export AWS_DEFAULT_REGION=us-east-1

# Activate virtual environment
source venv/bin/activate

# Add project-root/src to PYTHONPATH if it's not already present
if [[ ":$PYTHONPATH:" != *":$(pwd)/src:"* ]]; then
    export PYTHONPATH="$(pwd)/src:$PYTHONPATH"
fi
if [[ ":$PYTHONPATH:" != *":$(pwd)/tests:"* ]]; then
    export PYTHONPATH="$(pwd)/tests:$PYTHONPATH"
fi

# Remove duplicate entries from PYTHONPATH
export PYTHONPATH=$(echo "$PYTHONPATH" | awk -v RS=: -v ORS=: '!a[$1]++')

echo "final PYTHONPATH $PYTHONPATH"

# Install dependencies
# pip install -r requirements.txt

# pip install pytest-docker-compose

# Replace mock_aws and mock_aws2 with mock_aws
sed -i '' 's/mock_aws/mock_aws/g' $(find . -type f -name "*.py")
sed -i '' 's/mock_aws2/mock_aws/g' $(find . -type f -name "*.py")

# Run pytest
pytest $PYTEST_TARGET

# Deactivate virtual environment
deactivate

