#!/bin/bash

# Exit immediately if a command exits with a non-zero status
# set -e

# as defined in the .env file
export AWS_DEFAULT_REGION=us-west-2

# Activate virtual environment
source venv/bin/activate

# Add project-root/src to PYTHONPATH if it's not already present
if [[ ":$PYTHONPATH:" != *":$(pwd)/src:"* ]]; then
    export PYTHONPATH="$(pwd)/src:$PYTHONPATH"
fi

# Remove duplicate entries from PYTHONPATH
export PYTHONPATH=$(echo "$PYTHONPATH" | awk -v RS=: -v ORS=: '!a[$1]++')

echo "final PYTHONPATH $PYTHONPATH"

# Install dependencies
# pip install -r requirements.txt

# verify dockerdesktop is running
docker info
if [ "$?" -ne "0" ]; then
  echo "DockerDesktop is not accessible"
  exit 1
fi

# verify dynamodb is running
DYNAMODB_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:4566)
if [ "$DYNAMODB_STATUS" -ne 200 ]; then
  echo "DynamoDB is not running at http://localhost:4566"
  exit 1
else
  echo "verified that dynamodb is accessible at http://localhost:4566"
fi

# now start the app
python src/youtube_searcher_app.py
